export const RC_PEDAL_RICKSHAW_LOADING_REHRI = "CTL.REHRI_REGISTRATION";
export const DL_PEDAL_RICKSHAW_LOADING_REHRI = "CTL.REHRI_DRIVING_LICENSE";
export const LICENSE_DHOBI_GHAT = "CTL.DHOBI_GHAT";
export const RENEWAL_RENT_DEED_SHOP = "CTL.OLD_BOOK_MARKET";