version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ch-smart-city-22
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1200
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1200
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 1200
      runas: ec2-user
