import { getLocaleLabels } from "egov-ui-framework/ui-utils/commons";

export const RP_MASTER_ENTRY = "RP_MASTER_ENTRY";
export const PERMISSIONTOMORTGAGE = "PERMISSIONTOMORTGAGE";
export const OWNERSHIPTRANSFERRP = "OWNERSHIPTRANSFERRP";
export const TRANSITSITEIMAGES = "TRANSITSITEIMAGES";
export const DUPLICATECOPYOFALLOTMENTLETTERRP = "DUPLICATECOPYOFALLOTMENTLETTERRP";
export const RECOVERY_NOTICE = "RECOVERY_NOTICE";
export const VIOLATION_NOTICE = "VIOLATION_NOTICE";
export const NOTICE_GENERATION = "NOTICE_GENERATION";
export const RP_MONTH = getLocaleLabels("RP_MONTH", "RP_MONTH")
export const RP_ASSESSMENT_AMOUNT = getLocaleLabels("RP_ASSESSMENT_AMOUNT", "RP_ASSESSMENT_AMOUNT")
export const RP_REALIZATION_AMOUNT = getLocaleLabels("RP_REALIZATION_AMOUNT", "RP_REALIZATION_AMOUNT")
export const RP_RECEIPT_NO = getLocaleLabels("RP_RECEIPT_NO", "RP_RECEIPT_NO")