export const RP_MASTER_ENTRY = "RP_MASTER_ENTRY";
export const PERMISSIONTOMORTGAGE = "PERMISSIONTOMORTGAGE";
export const OWNERSHIPTRANSFERRP = "OWNERSHIPTRANSFERRP";
export const TRANSITSITEIMAGES = "TRANSITSITEIMAGES";
export const DUPLICATECOPYOFALLOTMENTLETTERRP = "DUPLICATECOPYOFALLOTMENTLETTERRP";
export const RECOVERY_NOTICE = "RECOVERY_NOTICE";
export const VIOLATION_NOTICE = "VIOLATION_NOTICE";
export const NOTICE_GENERATION = "NOTICE_GENERATION";